.TH FT_PING 1 "2026-09-29" "ft_ping 1.0.0" "User Commands"
.SH NAME
ft_ping \- send ICMP ECHO_REQUEST to network hosts
.SH SYNOPSIS
.B ft_ping
[\fIOPTIONS\fR] \fIHOST\fR
.SH DESCRIPTION
.B ft_ping
sends ICMP ECHO_REQUEST packets to network hosts.
.SH OPTIONS
.TP
.B \-v
Verbose output.
.TP
.B \-h
Show help.